# Generated by Django 3.0.7 on 2020-06-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_auto_20200612_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ('created',)},
        ),
    ]
