# Generated by Django 3.0.7 on 2020-06-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_auto_20200612_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique_for_date='created'),
        ),
    ]
